# ansible/roles/docker_provisioning/handlers/main.yml
---
# * ---------------------------------------------------------------------------------------- * #
# ?                            Docker Provisioning Role - Handlers                            * #
# * ---------------------------------------------------------------------------------------- * #

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  become: true

- name: Wait for Docker daemon
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 30
  become: true

- name: Stop docker
  ansible.builtin.systemd:
    name: docker
    state: stopped
  become: true

- name: Start docker
  ansible.builtin.systemd:
    name: docker
    state: started
    daemon_reload: true
  become: true

- name: Reload docker
  ansible.builtin.systemd:
    name: docker
    state: reloaded
    daemon_reload: true
  become: true

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
  become: true

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
  become: true
  when: ansible_os_family in ["RedHat", "Debian"]

- name: Prune docker system
  ansible.builtin.command:
    cmd: docker system prune -af --volumes
  become: true
  changed_when: true
  when: docker_provisioning_prune_on_restart | default(false)
