---
# ansible/roles/docker_provisioning/requirements.yml
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=6.0.0"
  - name: community.docker
    version: ">=3.0.0"
