# ansible/inventories/hosts.yml
---
all:
  hosts:
    # * ---------------------------------------------------------------------------------------- * #
    # *                                           PVEs                                           * #
    # * ---------------------------------------------------------------------------------------- * #
    pve-aigateway: &pve_aio_vars
      ansible_host: "{{ default_net_pve_aio_ip }}"
      ansible_user: "{{ pve_root_user_name }}"
    # * ---------------------------------------------------------------------------------------- * #
    # *                                           VMs                                            * #
    # * ---------------------------------------------------------------------------------------- * #
    vm05-commandcore: &vm05_commandcore_vars
      ansible_host: "{{ vm05_commandcore.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm08-workflownexus: &vm08_workflownexus_vars
      ansible_host: "{{ vm08_workflownexus.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm09-aigateway: &vm09_aigateway_vars
      ansible_host: "{{ vm09_aigateway.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm10-ingress: &vm10_ingress_vars
      ansible_host: "{{ vm10_ingress.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm20-metrics: &vm20_metrics_vars
      ansible_host: "{{ vm20_metrics.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm31-application-1: &vm31_application-1_vars
      ansible_host: "{{ vm31_application_1.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm41-multimedia-1: &vm41_multimedia-1_vars
      ansible_host: "{{ vm41_multimedia_1.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm60-ai-stuff: &vm60_ai_stuff_vars
      ansible_host: "{{ vm60_ai_stuff.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm81-coding-1: &vm81_coding_1_vars
      ansible_host: "{{ vm81_coding_1.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm90-testing-0: &vm90_testing_0_vars
      ansible_host: "{{ vm90_testing_0.ip }}"
      ansible_user: "{{ primary_user_name }}"
    vm91-testing-1: &vm91_testing_1_vars
      ansible_host: "{{ vm91_testing_1.ip }}"
      ansible_user: "{{ primary_user_name }}"
  # * ---------------------------------------------------------------------------------------- * #
  # ?                                       Environments                                       * #
  # * ---------------------------------------------------------------------------------------- * #
  children:
    prod:
      children:
        pve_servers_env_prod:
          hosts:
            pve-aigateway_env_prod: *pve_aio_vars
        prod_vms:
          hosts:
            prod-vm05-commandcore: *vm05_commandcore_vars
            prod-vm08-workflownexus: *vm08_workflownexus_vars
            prod-vm09-aigateway: *vm09_aigateway_vars
            prod-vm10-ingress: *vm10_ingress_vars
            prod-vm20-metrics: *vm20_metrics_vars
            prod-vm31-application-1: *vm31_application-1_vars
            prod-vm41-multimedia-1: *vm41_multimedia-1_vars
            prod-vm60-ai-stuff: *vm60_ai_stuff_vars
            prod-vm81-coding-1: *vm81_coding_1_vars
            prod-vm90-testing-0: *vm90_testing_0_vars
            prod-vm91-testing-1: *vm91_testing_1_vars
    beta:
    dev:
      children:
        pve_servers_env_dev:
          hosts:
            pve-aigateway_env_dev: *pve_aio_vars
        dev_vms:
          hosts:
            dev-vm05-commandcore: *vm05_commandcore_vars
            dev-vm08-workflownexus: *vm08_workflownexus_vars
            dev-vm09-aigateway: *vm09_aigateway_vars
            dev-vm10-ingress: *vm10_ingress_vars
            dev-vm20-metrics: *vm20_metrics_vars
            dev-vm31-application-1: *vm31_application-1_vars
            dev-vm41-multimedia-1: *vm41_multimedia-1_vars
            dev-vm60-ai-stuff: *vm60_ai_stuff_vars
            dev-vm81-coding-1: *vm81_coding_1_vars
            dev-vm90-testing-0: *vm90_testing_0_vars
            dev-vm91-testing-1: *vm91_testing_1_vars
    demo:
      children:
        pve_servers_env_demo:
          hosts:
            pve-aigateway_env_demo: *pve_aio_vars
        demo_vms:
          hosts:
            demo-vm05-commandcore: *vm05_commandcore_vars
            demo-vm08-workflownexus: *vm08_workflownexus_vars
            demo-vm09-aigateway: *vm09_aigateway_vars
            demo-vm10-ingress: *vm10_ingress_vars
            demo-vm20-metrics: *vm20_metrics_vars
            demo-vm31-application-1: *vm31_application-1_vars
            demo-vm41-multimedia-1: *vm41_multimedia-1_vars
            demo-vm60-ai-stuff: *vm60_ai_stuff_vars
            demo-vm81-coding-1: *vm81_coding_1_vars
            demo-vm90-testing-0: *vm90_testing_0_vars
            demo-vm91-testing-1: *vm91_testing_1_vars
