# ansible/roles/docker_provisioning/tasks/main.yml
---
# * ---------------------------------------------------------------------------------------- * #
# ?                          Docker Provisioning Role - Main Orchestrator                     * #
# * ---------------------------------------------------------------------------------------- * #
#
# This is the main task file that orchestrates the Docker provisioning process.
# It implements the three-pillar security model:
# 1. Host-Container Isolation (userns-remap)
# 2. Container-Container Isolation (Named Volumes)
# 3. Intra-Container Security (Non-root user)

# * ---------------------------------------------------------------------------------------- * #
# ?                                    Pre-Installation Phase                                 * #
# * ---------------------------------------------------------------------------------------- * #

- name: Run preflight checks
  ansible.builtin.import_tasks: preflight.yml
  tags:
    - docker
    - docker-preflight
    - preflight

- name: Setup host system for Docker
  ansible.builtin.import_tasks: host_setup.yml
  tags:
    - docker
    - docker-host
    - host-setup

- name: Create Docker filesystem structure
  ansible.builtin.import_tasks: filesystem.yml
  tags:
    - docker
    - docker-filesystem
    - filesystem

# * ---------------------------------------------------------------------------------------- * #
# ?                                    Installation Phase                                     * #
# * ---------------------------------------------------------------------------------------- * #

- name: Install Docker CE and docker-compose plugin
  ansible.builtin.import_tasks: install_docker.yml
  tags:
    - docker
    - docker-install
    - install

# * ---------------------------------------------------------------------------------------- * #
# ?                                    Configuration Phase                                    * #
# * ---------------------------------------------------------------------------------------- * #

- name: Configure Docker daemon
  ansible.builtin.import_tasks: daemon_config.yml
  tags:
    - docker
    - docker-config
    - config

- name: Configure Docker networking
  ansible.builtin.import_tasks: networking.yml
  tags:
    - docker
    - docker-network
    - network

- name: Apply security hardening
  ansible.builtin.import_tasks: security.yml
  tags:
    - docker
    - docker-security
    - security

# * ---------------------------------------------------------------------------------------- * #
# ?                                    Validation Phase                                       * #
# * ---------------------------------------------------------------------------------------- * #

- name: Run post-installation validation
  ansible.builtin.import_tasks: validation.yml
  tags:
    - docker
    - docker-validation
    - validation

# * ---------------------------------------------------------------------------------------- * #
# ?                                    Final Summary                                          * #
# * ---------------------------------------------------------------------------------------- * #

- name: Display provisioning completion summary
  ansible.builtin.debug:
    msg:
      - "╔════════════════════════════════════════════════════════════╗"
      - "║          Docker Provisioning Complete - ADR-001           ║"
      - "╠════════════════════════════════════════════════════════════╣"
      - "║ Three Pillars Security Model Successfully Implemented:     ║"
      - "║                                                            ║"
      - "║ ✓ Pillar 1: Host-Container Isolation                      ║"
      - "║   └─ userns-remap: {{ docker_provisioning_dockremap_user | ljust(39) }}║"
      - "║                                                            ║"
      - "║ ✓ Pillar 2: Container-Container Isolation                 ║"
      - "║   └─ Named Volumes enforced, ICC disabled                 ║"
      - "║                                                            ║"
      - "║ ✓ Pillar 3: Intra-Container Security                      ║"
      - "║   └─ Standard UID: {{ docker_provisioning_container_internal_uid | ljust(38) }}║"
      - "╠════════════════════════════════════════════════════════════╣"
      - "║ Security Tools Available:                                 ║"
      - "║   • {{ docker_provisioning_docker_root }}/scripts/security-compliance-check.sh"
      - "║   • {{ docker_provisioning_docker_root }}/scripts/docker-network-policy.sh"
      - "╚════════════════════════════════════════════════════════════╝"
  tags:
    - docker
    - docker-summary
    - always
