---
- name: Create Docker directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: "{{ docker.home }}", mode: '0750', owner: "{{ docker_provisioning_docker_user_name }}", group: "{{ docker_provisioning_docker_user_name }}" }
    - { path: "{{ docker.container_logs }}", mode: '0750', owner: "{{ docker_provisioning_docker_user_name }}", group: "{{ docker_provisioning_docker_user_name }}" }
    - { path: "{{ docker.container_secrets }}", mode: '0750', owner: "{{ docker_provisioning_docker_user_name }}", group: "{{ docker_provisioning_docker_user_name }}" }
